[package]
description = "Proc macros for using the playdate crate."
license = "MIT or Apache-2.0"
name = "playdate-macro"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = {version = "1", features = ["full"]}
