[workspace]
members = [
  "windup",
  "playdate-sys",
]

[package]
name = "simulator-win"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
windup = {path= "windup"}

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
