[workspace]
members = [
  "windup",
  "playdate-sys",
]

[package]
edition = "2021"
name = "simulator-win"
version = "0.1.0"

[lib]
crate-type = ["dylib"]

[dependencies]
windup = {path = "./windup"}

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
