[build]
target = "armv7a-none-eabi"

# Nice idea, but musleabi doesn't support linking. It just makes a staticlib.
#[target.arm-unknown-linux-musleabi]
#rustflags = [
#  "-Clink-arg=-fPIC",
#  "-C",
#  "linker-flavor=ld.lld",
#]
