[package]
name = "windup-build"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tiled = "0.10.1"
rusync = "0.7.2"
playdate-build = {path = "../playdate-build"}
windup-map = {path = "../windup-map"}