hard_tabs = false
tab_spaces = 2
#wrap_comments = true
comment_width = 100
max_width = 100
edition = "2021"
imports_indent = "Visual"
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
use_field_init_shorthand = true
version = "Two"

# use_small_heuristics = "Max"
chain_width = 100
